server:
  port: 7073
spring:
  application:
    name: eureka-client-stuInfo
     # 环境 dev:开发环境|test:测试环境|prod:生产环境
  profiles:
    active: prod #激活的配置文件
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetchRegistry: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true