spring: 
  datasource:
    username: sysqimeng
    password: 5871a39a16
    url: jdbc:mysql://47.107.118.156:3306/sysqimeng?useUnicode=true&characterEncoding=UTF-8&&serverTimezone=UTC
    
    driver-class-name: com.mysql.cj.jdbc.Driver
   #type: com.alibaba.druid.pool.DruidDataSource
      
      

  redis:
    database: 0   # Redis数据库索引（默认为0）  
    host: 127.0.0.1   
    port: 6379  
    password:   # Redis服务器连接密码（默认为空）   
    timeout: 1000 # 连接超时时间（毫秒）        
    maxIdle: 300 #最大空闲数
#连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
#maxActive=600
#控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
    maxTotal: 1000
#最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
    maxWaitMillis: 1000
#连接的最小空闲时间 默认1800000毫秒(30分钟)
    minEvictableIdleTimeMillis: 300000
#每次释放连接的最大数目,默认3
    numTestsPerEvictionRun: 1024
#逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
    timeBetweenEvictionRunsMillis: 30000
#是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    testOnBorrow: true
#在空闲时检查有效性, 默认false