server:
  port: 8074
spring:
  application:
    name: eureka-client-uesrmanage
     # 环境 dev:开发环境|test:测试环境|prod:生产环境
  profiles:
    active: dev #激活的配置文件
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      maxFileSize: 10MB
      maxRequestSize: 10MB
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetchRegistry: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
